### PR TITLE
Load Script strings from binary (Unity TextAsset)

### PR DESCRIPTION
**Pull request by IJEMIN**
On mobile file system with Unity, it's hard to access file via path.
What I do was reading script and strings files and re-write to other path which Unity can access on mobile.

I want to directly assign binaries(as TextAsset) in Inspector.

Loading script from bytes is already supported.
So I add tiny function to load strings from binary.

### CODE REVIEW

**Comment by eugeniusfox** [comment]
I see your point, but that would impose a specific binary format for storing the text strings; instead, a `Script.SetStrings` method could be added to digest a list of structures representing the text strings (*i.e.*, with a label, hash, and text property; it would be a public structure built into the library), so that the user (or any library built on top of VGPrompter) could store the strings however he would see fit and then provide his own parser.
Let me know what you think, and thank you for your input.

**Comment by IJEMIN** [comment]
For example, like this?

`SetString(string data, string[] splitPattern)`

1. User use strings data which serialized by VGP
-> use previous LoadStrings

2. User use strings data which it's structure made by his own
-> use SetStrings with his own pattern

,, and just get strings data, don't care about how user get strings in the outside of VGP?

That would be better!

**Comment by eugeniusfox** [comment]
That signature would be quite opaque, this is what I meant:

```csharp
public struct VGPString {
	public string Label { get; private set; }
	public string Hash { get; private set; }
	public string Text { get; private set; }
	
	public VGPString(string label, string hash, string text) : this() {
		Label = label;
		Hash = hash;
		Text = text;
	}
}
```

```csharp
public void SetStrings(List<VGPString> strings) {
	// ...
}
```

**Comment by IJEMIN** [comment]
Now I understand what you mean. :)
I guess you can close this request without merge.
And if you don't mind, I'll be back with that feature.

**Pull request closed without merging**
